import UrlTemplateImageryProvider2 from "../../to_cesium/Source/Scene/UrlTemplateImageryProvider2.js";
import TileCoordinatesImageryProvider2 from "../../to_cesium/Source/Scene/TileCoordinatesImageryProvider2.js";
import ArrowPointCloudImageryProvider from "../../to_cesium/Source/Scene/ArrowPointCloudImageryProvider.js";
(function(){
  document.addEventListener('DOMContentLoaded', function(){
    init()
  })
  function init(){
    v11.destroy();v12.destroy();v13.destroy();v21.destroy();v22.destroy();v23.destroy()
    v11=new Cesium.Viewer('v11',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new TileCoordinatesImageryProvider2({maximumLevel:maxZoom,minimumLevel:minZoom})})
    v12=new Cesium.Viewer('v12',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new ArrowPointCloudImageryProvider({maximumLevel:maxZoom,minimumLevel:minZoom,arrowDir:'tile_arrow/bufr_to_arrow/surface/synop',locationDatetimeDir:'indicator_location_datetime',uniqueKeyArray:['indicator', 'id'],propertyDir:'air_temperature',property:'air temperature [K]',year:'2020',monthDay:'0826',hour:'04',viewer:v11})})
    v13=new Cesium.Viewer('v13',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new ArrowPointCloudImageryProvider({maximumLevel:maxZoom,minimumLevel:minZoom,arrowDir:'tile_arrow/bufr_to_arrow/surface/synop',locationDatetimeDir:'indicator_location_datetime',uniqueKeyArray:['indicator', 'id'],propertyDir:'dewpoint_temperature',property:'dewpoint temperature [K]',year:'2020',monthDay:'0826',hour:'04',viewer:v12})})
    v21=new Cesium.Viewer('v21',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new Cesium.UrlTemplateImageryProvider({maximumLevel:maxZoom,minimumLevel:minZoom,tilingScheme:new Cesium.GeographicTilingScheme(),url:'tile/{z}/{x}/{reverseY}.png'})})
    v22=new Cesium.Viewer('v22',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new Cesium.UrlTemplateImageryProvider({maximumLevel:maxZoom,minimumLevel:minZoom,tilingScheme:new Cesium.GeographicTilingScheme(),url:'tile/{z}/{x}/{reverseY}.png'})})
    v23=new Cesium.Viewer('v23',{animation:false,baseLayerPicker:false,fullscreenButton:false,geocoder:false,homeButton:false,infoBox:false,sceneModePicker:false,selectionIndicator:false,timeline:false,navigationHelpButton:false,skyBox:false,skyAtmosphere:false,useBrowserRecommendedResolution:false,sceneMode:sMode,creditContainer:'c',requestRenderMode:true,imageryProvider:new Cesium.UrlTemplateImageryProvider({maximumLevel:maxZoom,minimumLevel:minZoom,tilingScheme:new Cesium.GeographicTilingScheme(),url:'tile/{z}/{x}/{reverseY}.png'})})
    v11.resolutionScale=vResolutionScale;v12.resolutionScale=vResolutionScale;v13.resolutionScale=vResolutionScale;v21.resolutionScale=vResolutionScale;v22.resolutionScale=vResolutionScale;v23.resolutionScale=vResolutionScale
    v11.scene.screenSpaceCameraController.minimumZoomDistance=minZoomDis;v12.scene.screenSpaceCameraController.minimumZoomDistance=minZoomDis;v13.scene.screenSpaceCameraController.minimumZoomDistance=minZoomDis
    v11.scene.screenSpaceCameraController.maximumZoomDistance=maxZoomDis;v12.scene.screenSpaceCameraController.maximumZoomDistance=maxZoomDis;v13.scene.screenSpaceCameraController.maximumZoomDistance=maxZoomDis
    v11.camera.percentageChanged=cPercentageChanged;v12.camera.percentageChanged=cPercentageChanged;v13.camera.percentageChanged=cPercentageChanged;v21.camera.percentageChanged=cPercentageChanged;v22.camera.percentageChanged=cPercentageChanged;v23.camera.percentageChanged=cPercentageChanged
    v11.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)});v12.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)});v13.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)});v21.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)});v22.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)});v23.camera.setView({destination:Cesium.Cartesian3.fromDegrees(cLon,cLat,cHeight)})
    v11.camera.changed.addEventListener(function(){v12.camera.position=v11.camera.position;v12.camera.direction=v11.camera.direction;v12.camera.up=v11.camera.up;v12.camera.right=v11.camera.right;v13.camera.position=v11.camera.position;v13.camera.direction=v11.camera.direction;v13.camera.up=v11.camera.up;v13.camera.right=v11.camera.right;v21.camera.position=v11.camera.position;v21.camera.direction=v11.camera.direction;v21.camera.up=v11.camera.up;v21.camera.right=v11.camera.right;v22.camera.position=v11.camera.position;v22.camera.direction=v11.camera.direction;v22.camera.up=v11.camera.up;v22.camera.right=v11.camera.right;v23.camera.position=v11.camera.position;v23.camera.direction=v11.camera.direction;v23.camera.up=v11.camera.up;v23.camera.right=v11.camera.right})
    v12.camera.changed.addEventListener(function(){v11.camera.position=v12.camera.position;v11.camera.direction=v12.camera.direction;v11.camera.up=v12.camera.up;v11.camera.right=v12.camera.right;v13.camera.position=v12.camera.position;v13.camera.direction=v12.camera.direction;v13.camera.up=v12.camera.up;v13.camera.right=v12.camera.right;v21.camera.position=v12.camera.position;v21.camera.direction=v12.camera.direction;v21.camera.up=v12.camera.up;v21.camera.right=v12.camera.right;v22.camera.position=v12.camera.position;v22.camera.direction=v12.camera.direction;v22.camera.up=v12.camera.up;v22.camera.right=v12.camera.right;v23.camera.position=v12.camera.position;v23.camera.direction=v12.camera.direction;v23.camera.up=v12.camera.up;v23.camera.right=v12.camera.right})
    v13.camera.changed.addEventListener(function(){v11.camera.position=v13.camera.position;v11.camera.direction=v13.camera.direction;v11.camera.up=v13.camera.up;v11.camera.right=v13.camera.right;v12.camera.position=v13.camera.position;v12.camera.direction=v13.camera.direction;v12.camera.up=v13.camera.up;v12.camera.right=v13.camera.right;v21.camera.position=v13.camera.position;v21.camera.direction=v13.camera.direction;v21.camera.up=v13.camera.up;v21.camera.right=v13.camera.right;v22.camera.position=v13.camera.position;v22.camera.direction=v13.camera.direction;v22.camera.up=v13.camera.up;v22.camera.right=v13.camera.right;v23.camera.position=v13.camera.position;v23.camera.direction=v13.camera.direction;v23.camera.up=v13.camera.up;v23.camera.right=v13.camera.right})
    v21.camera.changed.addEventListener(function(){v11.camera.position=v21.camera.position;v11.camera.direction=v21.camera.direction;v11.camera.up=v21.camera.up;v11.camera.right=v21.camera.right;v12.camera.position=v21.camera.position;v12.camera.direction=v21.camera.direction;v12.camera.up=v21.camera.up;v12.camera.right=v21.camera.right;v13.camera.position=v21.camera.position;v13.camera.direction=v21.camera.direction;v13.camera.up=v21.camera.up;v13.camera.right=v21.camera.right;v22.camera.position=v21.camera.position;v22.camera.direction=v21.camera.direction;v22.camera.up=v21.camera.up;v22.camera.right=v21.camera.right;v23.camera.position=v21.camera.position;v23.camera.direction=v21.camera.direction;v23.camera.up=v21.camera.up;v23.camera.right=v21.camera.right})
    v22.camera.changed.addEventListener(function(){v11.camera.position=v22.camera.position;v11.camera.direction=v22.camera.direction;v11.camera.up=v22.camera.up;v11.camera.right=v22.camera.right;v12.camera.position=v22.camera.position;v12.camera.direction=v22.camera.direction;v12.camera.up=v22.camera.up;v12.camera.right=v22.camera.right;v13.camera.position=v22.camera.position;v13.camera.direction=v22.camera.direction;v13.camera.up=v22.camera.up;v13.camera.right=v22.camera.right;v21.camera.position=v22.camera.position;v21.camera.direction=v22.camera.direction;v21.camera.up=v22.camera.up;v21.camera.right=v22.camera.right;v23.camera.position=v22.camera.position;v23.camera.direction=v22.camera.direction;v23.camera.up=v22.camera.up;v23.camera.right=v22.camera.right})
    v23.camera.changed.addEventListener(function(){v11.camera.position=v23.camera.position;v11.camera.direction=v23.camera.direction;v11.camera.up=v23.camera.up;v11.camera.right=v23.camera.right;v12.camera.position=v23.camera.position;v12.camera.direction=v23.camera.direction;v12.camera.up=v23.camera.up;v12.camera.right=v23.camera.right;v13.camera.position=v23.camera.position;v13.camera.direction=v23.camera.direction;v13.camera.up=v23.camera.up;v13.camera.right=v23.camera.right;v21.camera.position=v23.camera.position;v21.camera.direction=v23.camera.direction;v21.camera.up=v23.camera.up;v21.camera.right=v23.camera.right;v22.camera.position=v23.camera.position;v22.camera.direction=v23.camera.direction;v22.camera.up=v23.camera.up;v22.camera.right=v23.camera.right})
  }
}())